### ISSUE TITLE
Dynamically modify items

### ISSUE THREAD

**Issue by TimAEllis** [sarunw/SWSegmentedControl#3]
Hey, you say that this is a drop in replacement for `UISegmentedControl` yet it lacks the basic functionality of adding and removing segments at runtime like the `UISegmentedControl` can do.

Any plans to add this as it is a current blocker in using this?

**Comment by jovan90jovanovic** [comment]
You could do something like:

`extension SWSegmentedControl {
    
    func setItems(_ items: [String]) {
        for subview in self.subviews {
            subview.removeFromSuperview()
        }
        
        self.items = items
        self.commonInit()
    }
}`

but you'd have to change access control of commonInit() and items.

**Comment by TimAEllis** [comment]
Closing as a workaround has been provided
