### ISSUE TITLE
How do I change the font size of the segmented control button text

### ISSUE THREAD

**Issue by tobitech** [sarunw/SWSegmentedControl#8]
Hello! Nice work. I want you to please help with changing the font size of the segmented control button texts. In which method can I add this ```button.titleLabel?.font = UIFont.systemFont(ofSize: 13)```?

**Comment by tobitech** [comment]
Okay I was able to do it by setting it inside the configureButton()

**Comment by joecutter** [comment]
Hey were you able to set  actions when slide is changed?
